meta_product_name : « PharmaStock »

meta_title : « PharmaStock – Pour le stock pharma et veto »

meta_description : « Description pertinente »

meta_image : "panier-pharma.png" # devrait exister dans `app/assets/images/`

twitter_account : « @product_twitter_account » # requis pour les cartes Twitter
